server:
  port: 8881  # 服务端口

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mfblog?useSSL=false&serverTimezone=UTC  # 数据库连接 URL
    username: root  # 数据库用户名
    password: 123456  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  # 数据库驱动
  jpa:
    hibernate:
      ddl-auto: update  # 数据库表结构自动更新策略
    show-sql: true  # 在控制台打印生成的 SQL 语句

logging:
  level:
    root: info  # 日志级别

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      pagination-type: pagehelper